jump-dev/MutableArithmetics.jl

Project.toml, src/MutableArithmetics.jl, test/runtests.jl
Adds the `LinearAlgebra.mul!` operation for types `<: AbstractMutable`, and the tests for it using `DummyBigInt`.
=> Move code from the IJulia notebooks

src/MutableArithmetics.jl, src/Test/int.jl, src/bigint.jl, src/interface.jl, src/linear_algebra.jl, src/shortcuts.jl, test/int.jl, test/matmul.jl
This enforces a consistent behaviors between `add!`, `add_to!` and `mul!`, `mul_to!`, ...
=> Refactor with operate functions

.travis.yml, Project.toml, src/MutableArithmetics.jl, src/bigint.jl, src/broadcast.jl, src/dispatch.jl, src/interface.jl, src/linear_algebra.jl, src/rewrite.jl, src/shortcuts.jl, src/sparse_arrays.jl, test/broadcast.jl, test/int.jl, test/rewrite.jl, test/runtests.jl
The `@rewrite` macro rewrites an expression as a code that exploits the mutability of the arithmetic (if any) using `MA.operate!`.
It is heavily inspired from JuMP's `_parse_expr` function.
=> Add @rewrite macro

docs/Manifest.toml, docs/src/index.md, src/MutableArithmetics.jl, src/bigint.jl, src/dispatch.jl, src/interface.jl, src/linear_algebra.jl, src/rewrite.jl, src/shortcuts.jl, src/sparse_arrays.jl, test/dummy.jl, test/matmul.jl, test/rewrite.jl, test/runtests.jl, test/utilities.jl
Generalises JuMP's rewrite of some linear algebra operation on dense and sparse arrays to arbitrary mutable types.
=> Mutable array operations

src/bigint.jl, src/interface.jl, src/linear_algebra.jl, src/shortcuts.jl, test/dummy.jl, test/interface.jl, test/operations.jl, test/runtests.jl
It turns out, it is only used by `BigInt` so it's better to give more control over the types implementing MA for this.
Moreover, for polynomials of MultivariatePolynomials, this redirection does not work as the first argument of `operate_to` should be different than the other arguments.
=> Don't automatically redirect operate to operate_to

README.md, src/MutableArithmetics.jl, src/bigfloat.jl, test/bigfloat.jl, test/rewrite.jl, test/runtests.jl
Inspired from https://peiffap.wordpress.com/2019/08/26/gsoc-19-a-summary/
Closes https://github.com/JuliaOpt/MutableArithmetics.jl/issues/24
=> Implement MA API for BigFloat

src/MutableArithmetics.jl, src/dispatch.jl, src/interface.jl, src/linear_algebra.jl, src/reduce.jl, src/rewrite.jl, src/shortcuts.jl, test/matmul.jl
This also improves performance of `@rewrite` as `@rewrite(x * y + z)` does not call `copy_if_mutable` on `x * y`, it instead call `operate(*, x, y)`.
=> Add operate function

src/Test/scalar.jl, src/rewrite.jl, test/rewrite.jl
Closes https://github.com/JuliaOpt/MutableArithmetics.jl/issues/31
=> Fix @rewrite for empty sum

src/sparse_arrays.jl
The un-exported function `SparseArrays.ilog2` is used here without qualification, causing an `UndefError` whenver the `prefer_sort` function is called.
It would be appreciated if there could be a tag after this, because currently this is breaking sparse arrays in JuMP 0.21 in rather unpredictable ways.
=> fixed ilog2 function missing from scope

src/rewrite.jl
I started fixing a bug for Julia 1.6, and got thoroughly confused
with what this function was doing. Hopefully this is more readable.
=> Add comments and tidy _rewrite function.

.github/workflows/ci.yml, Project.toml, src/rewrite.jl, test/dummy.jl
A PR to track fixes for 1.6. Tests fail at present.
=> Add 1.6 to CI

src/rewrite.jl, test/rewrite.jl
Closes #43
Easiest solution is just to only apply the rewrite if it is a `sum`.
=> Only rewrite generator if it is a sum

src/interface.jl
Needed for https://github.com/kalmarek/GroupsCore.jl/pull/21
=> operate on one and zero pass value not type

src/interface.jl, src/linear_algebra.jl, test/interface.jl, test/matmul.jl
Needed for https://github.com/JuliaMath/Polynomials.jl/pull/331
=> Buffered matrix multiplication

.github/workflows/ci.yml, src/dispatch.jl
https://github.com/JuliaLang/julia/pull/38789 has been merged, we can now overload a documenter and without underscore `iszerodefined` function instead of the internal `_iszero`.
=>  _iszero -> iszerodefined

src/MutableArithmetics.jl, src/dispatch.jl, src/interface.jl, src/linear_algebra.jl, src/reduce.jl, src/shortcuts.jl, test/dispatch.jl, test/dummy.jl, test/matmul.jl, test/runtests.jl, test/utilities.jl
https://github.com/JuliaLang/julia/pull/36679 introduced a new function `_dot_nonrecursive`.
While this function does not exploit mutability, several methods redirect to it so implementing it allows to kill a few birds with one stone.
Our implementation of `dot` wasn't really correct since we didn't call `dot` recursively so this PR also fixes that.
=> Implement dot_nonrecursive and add fused_map_reduce

src/broadcast.jl, test/broadcast.jl
Consider the function:
```julia                                                                                                                                      
function f()                                                                                                                               
a = [1, 2]
b = [3, 4]
@time MA.broadcast!(+, a, b)
end
```
On Julia v1.6.1, before this PR, I get `(8 allocations: 304 bytes)` and after I get no allocations.
There is still some allocations for some other case (see the tests) but I could not figure out where it comes from (similarly to https://github.com/jump-dev/MathOptInterface.jl/issues/1353 where I couldn't figure out either). I may be missing something.
=> Remove allocation in broadcast

src/interface.jl, src/shortcuts.jl, test/int.jl, test/interface.jl
See https://github.com/jump-dev/SumOfSquares.jl/pull/197/checks?check_run_id=2807131734#step:6:185
Also fixes method ambiguity that prevented the helpful error message to be displayed for https://discourse.julialang.org/t/list-comprehension-of-jump-variables/62848/4.
=> Fix ambiguity of / with MOI

src/bigfloat.jl, src/bigint.jl
The `deepcopy` in Base creates an `IDDict` to keep track of already copied values:
https://github.com/JuliaLang/julia/blob/60e3e5527f0395d32fe2d59d3eb6c0a5cf59d354/base/deepcopy.jl#L26
However, in our case, this is not needed and we might as well just inline the definition of `deepcopy_internal` without the dictionary. This makes us rely on some of the internals of `MPFR` and `GMP` but this package already does that heavily so might as well go "all in" in that case.
On master the performance is:
```jl
julia> using MutableArithmetics, BenchmarkTools
julia> bf, bi = big"1.0", big"1";
julia> @btime MutableArithmetics.mutable_copy($bf);
89.067 ns (5 allocations: 464 bytes)
julia> @btime MutableArithmetics.mutable_copy($bi);
119.106 ns (4 allocations: 376 bytes)
```
while on this PR it is: …
=> optimize `mutable_copy` on `BigFloat` and `BigInt`

src/dispatch.jl
New `mul!` methods were added in https://github.com/JuliaLang/julia/pull/29634/ so we now have to add methods to fix ambiguities.
=> Fix ambiguity with new mul! methods in Julia v1.7

src/dispatch.jl
`mat_mat_scalar` was added in https://github.com/JuliaLang/julia/pull/37898/ which is included in Julia v1.7.
It uses `promote_type` instead of `Base.promote_op` to determine the type of the resulting array so it won't work for instance when multiplying two matrices of JuMP affine expressions, it won't see that it needs quadratic expressions.
=> Workaround for mat_mat_scalar

README.md
This was changed deprecated in Documenter.jl 0.20.0 and dropped in 0.24.0
=> README.md: update latest -> dev in doc URLs

src/MutableArithmetics.jl, src/implementations/BigFloat.jl, src/implementations/BigInt.jl, src/implementations/LinearAlgebra.jl, src/implementations/MutatingStepRange.jl, src/implementations/Rational.jl, src/implementations/SparseArrays.jl
This PR refactors the implementations for specific types into an `/src/implementations` sub-directory to make the code easier to navigate.
=> Refactor implementations into subdir

src/interface.jl
Closes #132
As I suspected, the cause of #132 is some of the dispatch choices for when Julia specializes.
Before:
```julia
julia> @btime direct(100);
476.903 ns (3 allocations: 2.67 KiB)
julia> @btime no_rewrite(100);
19.890 μs (399 allocations: 262.59 KiB)
julia> @btime rewrite(100);
30.507 μs (9 allocations: 5.14 KiB)
julia> @btime linear_algebra(100);
96.442 μs (9 allocations: 5.12 KiB)
```
After (incl. https://github.com/jump-dev/MathOptInterface.jl/pull/1731):
```julia
julia> @btime direct(100);
477.354 ns (3 allocations: 2.67 KiB)
julia> @btime no_rewrite(100);
19.913 μs (399 allocations: 262.59 KiB)
julia> @btime rewrite(100);
1.634 μs (9 allocations: 5.14 KiB)
julia> @btime manual(100);
1.523 μs (9 allocations: 5.12 KiB)
julia> @btime linear_algebra(100);
1.616 μs (9 allocations: …
```
=> Improve performance of LinearAlgebra.dot

src/implementations/LinearAlgebra.jl, test/matmul.jl
Closes #65 
The original test case:
```Julia
julia> using JuMP, GLPK, StaticArrays
julia> model = Model(GLPK.Optimizer)
A JuMP Model
Feasibility problem with:
Variables: 0
Model mode: AUTOMATIC
CachingOptimizer state: EMPTY_OPTIMIZER
Solver name: GLPK
julia> @variable(model, 0 <= x <= 10)
x
julia> @variable(model, -10 <= y <= 3.4);
julia> A = SA[1.2 -2; 3 4]  # a SArray
2×2 SMatrix{2, 2, Float64, 4} with indices SOneTo(2)×SOneTo(2):
1.2  -2.0
3.0   4.0
julia> @constraint(model, con, A*[x, y] .<= 0)
2-element Vector{ConstraintRef{Model, MathOptInterface.ConstraintIndex{MathOptInterface.ScalarAffineFunction{Float64}, MathOptInterface.LessThan{Float64}}, ScalarShape}}:
con : 1.2 x - 2 y ≤ 0.0
con : 3 x + 4 y ≤ 0.0
```
=> Fix for StaticArrays in multiplication

.github/workflows/ci.yml, .github/workflows/documentation.yml, Project.toml, src/Test/array.jl, src/dispatch.jl, src/implementations/BigFloat.jl, test/big.jl, test/broadcast.jl, test/dispatch.jl, test/matmul.jl
I think it makes sense at this point to drop support for Julia <1.6 in all v1.0 releases in JuMP-dev.
=> Prep for v1.0 release and drop support for pre Julia 1.6 versions

src/interface.jl, src/reduce.jl, test/dispatch.jl
Closes #92
This results in a few more allocations, but it fixes incorrect behavior.
In particular, `master` currently produces:
```julia
julia> x = [5.0, 6.0]
2-element Vector{Float64}:
5.0
6.0
julia> y = Vector{Union{Float64,String}}(x)
2-element Vector{Union{Float64, String}}:
5.0
6.0
julia> MA.operate(*, x', y)
ERROR: MethodError: no method matching zero(::Type{Union{Float64, String}})
Closest candidates are:
zero(::Union{Type{P}, P}) where P<:Dates.Period at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Dates/src/periods.jl:53
zero(::JuMP.GenericQuadExpr) at /Users/oscar/.julia/packages/JuMP/Z1pVn/src/quad_expr.jl:109
zero(::JuMP.GenericAffExpr) at /Users/oscar/.julia/packages/JuMP/Z1pVn/src/aff_expr.jl:192
...
Stacktrace:
[1] …
```
=> Fix implementation of fused_map_reduce

Project.toml, src/implementations/SparseArrays.jl, test/SparseArrays.jl, test/runtests.jl
There are large swathes of the `SparseArrays.jl` interface that are untested, and even the bits that are tested have bugs:
https://app.codecov.io/gh/jump-dev/MutableArithmetics.jl/blob/master/src/implementations/SparseArrays.jl
Closes #37
=> Add tests and fix for SparseArray matrix multiplication

src/implementations/LinearAlgebra.jl, test/matmul.jl
=> Fix generic matmult in LinearAlgebra.jl

src/implementations/SparseArrays.jl
Issue: MutableArithmetics for SparseArrays is broken on nightly Julia because SparseArrays.ilog2 doesn't exist anymore.
This adds the function _top_set_bit and uses it instead of ilog2.
See
https://github.com/JuliaSparse/SparseArrays.jl/pull/324 and
https://github.com/JuliaLang/julia/pull/47523
=> SparseArrays: fix for nightly Julia, ilog2 -> top_set_bit

src/MutableArithmetics.jl, src/Test/int.jl, src/implementations/Rational.jl, test/big.jl
```julia
using MutableArithmetics
using BenchmarkTools
function non_mutable()
T = Rational{BigInt}
a = one(T)
b = one(T)
c = one(T)
@benchmark $a + $b * $c
end
function mutable()
T = Rational{BigInt}
a = one(T)
b = one(T)
c = one(T)
buffer = buffer_for(add_mul, T, T, T)
@benchmark buffered_operate!($buffer, add_mul, $a, $b, $c)
end
julia> non_mutable()
BenchmarkTools.Trial: 10000 samples with 550 evaluations.
Range (min … max):  208.478 ns … 24.738 μs  ┊ GC (min … max):  0.00% … 59.11%
Time  (median):     234.192 ns              ┊ GC (median):     0.00%
Time  (mean ± σ):   399.755 ns ±  1.942 μs  ┊ GC (mean ± σ):  23.80% ±  4.82%
▄▅▄▅███▆▅▄▃▃▂▁▂▁▁▁                                           ▂
████████████████████▇▇▇▇▇▆▇███▇▆▅▅▅▅▄▅▅▆▅▆▆▅▃▃▄▃▃▃▃▅▃▃▁▃▅▄▅▃ █
208 ns        Histogram: …
```
=> 0-allocation add_mul for Rational{BigInt}

src/rewrite.jl, test/rewrite.jl, test/rewrite_generic.jl
This is preventing JuMP from working with `DimensionalData.jl`: https://github.com/jump-dev/JuMP.jl/issues/3214#issuecomment-1430265935, or indeed, any types which implement `getindex(x; kwargs...)`. (The trick is that `x[a=1]` lowers to `getindex(x; a = 1)`.)
I think this was originally added so that people writing `@variable(model, x[a=1:2])` would get an error if they typed `@constraint(model, x[a=1] <= 1)`, but it seems like breaking other code is worse than providing a better error message is people mis-use JuMP containers.
This will break the JuMP tests for the same reason that https://github.com/jump-dev/JuMP.jl/pull/3125/files#diff-1506a102465c4b93f811ff0af5bf5b358e8a13a46eefab5fe5d77c8aab4bb0f9R641 does.
=> Support x[;kwargs...] syntax in rewrite macro

src/Test/Test.jl, src/rewrite.jl, test/SparseArrays.jl, test/broadcast.jl, test/dummy.jl, test/hygiene.jl, test/int.jl, test/interface.jl, test/matmul.jl, test/range.jl, test/rewrite.jl, test/rewrite_generic.jl, test/runtests.jl
x-ref https://github.com/jump-dev/JuMP.jl/pull/3222
Changing to `import MutableArithmetics as NewSymbolMA` in the test helped catch a couple of hygiene issues which expected the `MutableArithmetics` symbol to be in the namespace of any rewrites.
=> Use import MutableArithmetics as MA and fix resulting hygiene issue

src/MutableArithmetics.jl, src/evalpoly.jl, src/implementations/BigFloat.jl, src/interface.jl, test/evalpoly.jl, test/runtests.jl
```
julia> setprecision(512)
512
julia> @benchmark evalpoly(x, coefs) setup=(x = rand(BigFloat); coefs = rand(BigFloat, 10);)
BenchmarkTools.Trial: 10000 samples with 10 evaluations.
Range (min … max):  1.247 μs … 276.376 μs  ┊ GC (min … max): 0.00% … 96.44%
Time  (median):     1.487 μs               ┊ GC (median):    0.00%
Time  (mean ± σ):   1.611 μs ±   3.876 μs  ┊ GC (mean ± σ):  3.30% ±  1.37%
▁▃▄▇█▇▃
▂▂▂▃▄▆████████▇▅▄▃▄▄▄▅▅▅▅▅▅▄▅▄▄▃▃▃▃▃▂▂▂▂▂▂▂▂▂▁▁▂▂▂▂▂▂▂▂▂▂▂▂ ▃
1.25 μs         Histogram: frequency by time        2.41 μs <
Memory estimate: 1.20 KiB, allocs estimate: 18.
julia> @benchmark MA.operate(evalpoly, x, coefs) setup=(x = rand(BigFloat); coefs = rand(BigFloat, 10);)
BenchmarkTools.Trial: 10000 samples with 10 evaluations.
Range (min … max):  1.119 μs …   3.092 μs  ┊ GC (min … …
```
=> add evalpoly

Project.toml, src/dispatch.jl
This move avoids conflicts that may occur with slightly changing the use of the type parameter in https://github.com/JuliaLang/julia/pull/49521. It is necessary because in that linalg file, the `Blas*` restriction is usually used in the place of the eltype of the `StridedArray`, and not as the eltype of the `Adjoint` or `Transpose`. Moving the definition here into the VERSION branch neatly adopts that change and makes the package run smoothly across v1.6 - v1.10.
=> use `StridedMaybeAdjOrTransMat` instead of defining it

src/broadcast.jl, test/broadcast.jl
=> Fix broadcasting for non-DefaultArrayStyle containers

src/rewrite_generic.jl, test/rewrite_generic.jl
Closes https://github.com/jump-dev/MutableArithmetics.jl/issues/224
TODO
=> Fix rewrite of +(x, *(y...)) into add_mul

Project.toml, src/rewrite_generic.jl, test/rewrite_generic.jl
=> Fix bug rewriting sum with dims kwarg

src/implementations/LinearAlgebra.jl, test/interface.jl
=> Add support for BitVector and BitArray in operate

test/interface.jl
Currently the test set starts with the line
`@testset "$(typeof(x))" for x in [2, big(3)]`, which points to the test not working as intended, because the array constructor (`[2, big(3)]`) promotes all elements to a common type, so naming the test set `"$(typeof(x))"` doesn't make sense.
Furthermore, after the above is fixed, the test fails because the `!==` check is performed independently of whether the type is mutable.
TODO: including `Rational{BigInt}` among the tested types reveals what
seems to be a bug: #240.
TODO: including `abs` among the tested operations reveals that it lacks
an `operate` method: #241.
=> Fix incorrect `operate` test set

src/interface.jl, test/interface.jl
=> add an `operate` method for `abs`

src/dispatch.jl
=> dispatch.jl: simplify overloads for SparseMatrix * AbstractArray

src/implementations/LinearAlgebra.jl, test/interface.jl
Replaces https://github.com/jump-dev/JuMP.jl/pull/3295
Part of #206
=> Add similar_array_type for LinearAlgebra.Diagonal

src/implementations/BigFloat.jl, src/implementations/BigInt.jl, src/implementations/Rational.jl, src/interface.jl, test/copy.jl, test/interface.jl, test/runtests.jl
=> `copy` for `BigInt`, `BigFloat` and `Rational`

src/dispatch.jl, test/dummy.jl, test/rewrite.jl
Closes #234 
Closes #236
I've added @araujoms as a co-author to this commit.
=> Add dispatch for LinearAlgebra.dot for Symmetric and Hermitian matrices

src/implementations/LinearAlgebra.jl, test/matmul.jl
Closes #251
The previous implementations were incorrect because they did not account for non-`Base.OneTo` axes.
=> Fix implementation of mul! for AbstractMatrix and AbstractVector

test/matmul.jl
The wording of this error was set by `Base`, not by us.
=> Fix test for nightly

src/dispatch.jl, test/dispatch.jl
=> Fix multiplying Symmetric and Hermitian matrices

src/implementations/LinearAlgebra.jl, test/matmul.jl
This is important when using `MultivariatePolynomials.Term` to infer that the `eltype` of the result is `Term` and not `Polynomial`.
=> Fix promotion of outer product

src/interface.jl, test/interface.jl, test/matmul.jl
=> Fix mutability check for array multiplication

src/dispatch.jl, src/implementations/LinearAlgebra.jl, test/dispatch.jl
Needed for https://github.com/JuliaAlgebra/StarAlgebras.jl/pull/21
=> Add corresponding operate_to! method for Matrix-scalar product

src/implementations/LinearAlgebra.jl, test/matmul.jl
Turns out `broadcast!` is well implemented for SparseArrays:
```julia
julia> v = sparsevec([1, 3], [π, 2π])
3-element SparseVector{Float64, Int64} with 2 stored entries:
[1]  =  3.14159
[3]  =  6.28319
julia> a = copy(v)
3-element SparseVector{Float64, Int64} with 2 stored entries:
[1]  =  3.14159
[3]  =  6.28319
julia> b = copy(v)
3-element SparseVector{Float64, Int64} with 2 stored entries:
[1]  =  3.14159
[3]  =  6.28319
julia> @btime Broadcast.broadcast!(+, $v, 3, $a, 2, $b)
38.791 ns (0 allocations: 0 bytes)
3-element SparseVector{Float64, Int64} with 3 stored entries:
[1]  =  11.2832
[2]  =  5.0
[3]  =  17.5664
julia> @btime Broadcast.broadcast!(-, $v, 3, $a)
27.560 ns (0 allocations: 0 bytes)
3-element SparseVector{Float64, Int64} with 3 stored entries:
[1]  =  -0.141593
[2]  = …
```
=> Mutable addition and substraction of sparse arrays

src/rewrite.jl, test/rewrite.jl
x-ref https://github.com/jump-dev/JuMP.jl/pull/3737#issuecomment-2075890315
=> Implement performance optimization of promote_operation for *(::Any, ::Zero)

src/implementations/LinearAlgebra.jl, test/matmul.jl
Needed to fix the last broken test of https://github.com/JuliaAlgebra/StarAlgebras.jl/pull/32
=> Mutable addition of one array into result

src/broadcast.jl, test/broadcast.jl
Closes #295
The previous check for `length` is incorrect because it ignores length 1 dimensions. But the comment explains some arrays do not support size. Which? `SparseAxisArray`? Do we really support broadcasting over that?
=> Fix size check of arrays when broadcasting

src/rewrite_generic.jl, test/rewrite_generic.jl
=> Recurse rewrite_generic into :if and :block

src/dispatch.jl, src/reduce.jl, test/dispatch.jl
Closes https://github.com/jump-dev/MutableArithmetics.jl/issues/305
=> Allow init argument for sum

src/rewrite.jl, test/rewrite_generic.jl
Required for https://github.com/jump-dev/JuMP.jl/issues/3882
JuMP needs the ability to tell if it is safe to mutate the returned expression.
=> Add return_is_mutable kwarg to MA.rewrite

src/rewrite_generic.jl, test/rewrite_generic.jl
=> Fix unary minus operators in rewrite

src/rewrite_generic.jl, test/rewrite_generic.jl
I thought @joaquimg's suggestion (3) in https://github.com/NREL-Sienna/PowerSimulations.jl/pull/1218 was weird. It's because we weren't optimizing this case.
Before
```Julia
julia> model = Model();
julia> @variable(model, x)
x
julia> a, b = 2.0, 3.0
(2.0, 3.0)
julia> @allocated @expression(model, a * x * b)
1728
```
After
```julia
julia> model = Model();
julia> @variable(model, x)
x
julia> a, b = 2.0, 3.0
(2.0, 3.0)
julia> @allocated @expression(model, a * x * b)
1152
```
Before code:
```julia
julia> @macroexpand @expression(model, a * x * b)
quote
#= REPL[66]:1 =#
JuMP._valid_model(model, :model)
begin
#= /Users/oscar/.julia/packages/JuMP/CU7H5/src/macros.jl:399 =#
let model = model
#= /Users/oscar/.julia/packages/JuMP/CU7H5/src/macros.jl:400 =#
begin
#= …
```
=> Fix mutable allocations in n-ary multiplication

src/rewrite.jl, test/rewrite.jl
Fix #331 
I also added equality definitions - if this is desired. However, it would be a breaking change - `iszero` and `isone` were simply not defined, so this is fine, but comparison with `Zero` went to the `===` fallback before and returned `false`. So I understand if you'd rather not have these comparisons.
=> Checks for zeroness
