docs/make.jl

This should fix the documentation.

Add Travis to make.jl

---

src/linear_algebra.jl

@Peiffap I thought the first `@inbounds` was on the first `for`, the indent should help readability
See https://github.com/JuliaOpt/MutableArithmetics.jl/pull/12/files#r335907834

Remove nested @inbounds

---

src/MutableArithmetics.jl
src/Test/sparse.jl
src/broadcast.jl
src/sparse_arrays.jl

Closes https://github.com/JuliaOpt/MutableArithmetics.jl/issues/38

Fix broadcast with sparse arrays

---

src/Test/array.jl
src/linear_algebra.jl
test/dummy.jl

Fixes the issues reported in https://github.com/JuliaOpt/MathOptInterface.jl/issues/654#issuecomment-589584875

Fix promotion with adjoint and transpose

---

src/Test/array.jl
src/Test/scalar.jl
src/rewrite.jl

Closes https://github.com/JuliaOpt/MutableArithmetics.jl/issues/41

Fix @rewrite with product and vectorized

---

src/Test/scalar.jl
src/rewrite.jl

I don't fully understand if this is the correct fix. But it seems to work.
Closes #44

Fix bugs with empty sums

---

.travis.yml
src/dispatch.jl

Thanks to https://github.com/JuliaLang/julia/pull/36194

Remove _iszero hack on Julia nightly

---

src/linear_algebra.jl
test/matmul.jl

Closes #54 
@blegat: why the `zero!`?

Fix bug in matrix add_mul

---

src/rewrite.jl
test/int.jl

Closes https://github.com/jump-dev/MutableArithmetics.jl/issues/52

Implement division of Zero

---

.JuliaFormatter
docs/make.jl
src/MutableArithmetics.jl
src/Test/array.jl
src/Test/config.jl
src/Test/int.jl
src/Test/quadratic.jl
src/Test/scalar.jl
src/Test/sparse.jl
src/bigfloat.jl
src/bigint.jl
src/broadcast.jl
src/dispatch.jl
src/interface.jl
src/linear_algebra.jl
src/reduce.jl
src/rewrite.jl
src/shortcuts.jl
src/sparse_arrays.jl
test/dummy.jl
test/hygiene.jl
test/int.jl
test/interface.jl
test/matmul.jl
test/rewrite.jl

This PR formats the repo using the standard config used by JuMP and MathOptInterface.

Format using JuliaFormatter

---

Project.toml

Let's get this release out ASAP so we can fix any other issues for 1.6.

Bump to v0.2.14

---

src/linear_algebra.jl
test/matmul.jl

Closes https://github.com/jump-dev/MutableArithmetics.jl/issues/48
Closes #72

Fix bug in mutable_operate! with multiple arrays

---

src/Test/array.jl

See https://github.com/jump-dev/MutableArithmetics.jl/pull/77/files#r610927202

Add test for Matrix + Scaling * Scaling * Matrix

---

src/Test/array.jl
src/dispatch.jl

Closes https://github.com/jump-dev/MutableArithmetics.jl/issues/63

Fix ambiguity for mul! of two transpose/adjoint

---

src/rewrite.jl
test/rewrite.jl

Closes https://github.com/jump-dev/MutableArithmetics.jl/issues/79

Implement unary - for Zero

---

src/MutableArithmetics.jl
src/Test/array.jl
src/bigfloat.jl
src/bigint.jl
src/linear_algebra.jl
test/matmul.jl
test/rewrite.jl

Closes https://github.com/jump-dev/MutableArithmetics.jl/issues/76
Closes https://github.com/jump-dev/MutableArithmetics.jl/issues/53

Add +/- with AbstractArray

---

Project.toml
src/Test/array.jl
test/rewrite.jl

Exclude some tests for non-square arrays

---

src/Test/array.jl
test/rewrite.jl

Closes https://github.com/jump-dev/MutableArithmetics.jl/issues/96

Avoid multiplying for quadratic functions

---

README.md

Done in https://github.com/JuliaMath/Polynomials.jl/pull/331

Add Polynomials.jl in README

---

src/dispatch.jl
test/matmul.jl

Closes https://github.com/jump-dev/JuMP.jl/issues/2622

Nice error message in case of unsupported matrix product

---

src/MutableArithmetics.jl
src/bigfloat.jl
src/broadcast.jl
src/dispatch.jl
src/linear_algebra.jl
src/rewrite.jl
src/sparse_arrays.jl

This PR also moves some symbols to internal hence it is breaking.
Closes https://github.com/jump-dev/MutableArithmetics.jl/issues/110

Export all non-internal symbols

---

src/broadcast.jl
src/interface.jl
test/int.jl

Closes https://github.com/jump-dev/MutableArithmetics.jl/issues/108

NotMutable -> IsNotMutable

---

src/MutableArithmetics.jl
src/Test/array.jl
src/Test/int.jl
src/Test/scalar.jl
src/bigfloat.jl
src/bigint.jl
src/broadcast.jl
src/dispatch.jl
src/interface.jl
src/linear_algebra.jl
src/rational.jl
src/reduce.jl
src/rewrite.jl
src/shortcuts.jl
src/sparse_arrays.jl
test/big.jl
test/broadcast.jl
test/dummy.jl
test/int.jl
test/interface.jl
test/matmul.jl

Closes https://github.com/jump-dev/MutableArithmetics.jl/issues/107

Renaming following BangBang.jl convention

---

src/MutableArithmetics.jl
src/range.jl
test/range.jl
test/runtests.jl

See https://github.com/JuliaLang/julia/issues/39008

Mutating step range

---

src/dispatch.jl

Minor changes. Largely just me reading through the code to try and understand everything again.

Style improvements in dispatch.jl

---

src/broadcast.jl

Minor changes. Largely just me reading through the code to try and understand everything again.

Style imrpovements in broadcast.jl

---

src/MutableArithmetics.jl
src/rewrite.jl

Minor changes. Largely just me reading through the code to try and understand everything again.

Style improvements for rewrite.jl

---

src/reduce.jl

Minor changes. Largely just me reading through the code to try and understand everything again.

Style improvements in reduce.jl

---

.github/workflows/aqua.yml
src/Test/config.jl
src/interface.jl

Follow-up from https://github.com/jump-dev/MutableArithmetics.jl/pull/147

Add Aqua.jl as a CI job

---

src/interface.jl

Clarify docstring of operate_to

---

src/Test/array.jl
src/dispatch.jl

Solves https://github.com/jump-dev/MutableArithmetics.jl/issues/152
I looked at https://github.com/jump-dev/MutableArithmetics.jl/pull/89/files for inspiration but not sure if I got it right.

add `mul!` for `AbstractTriangular`

---

src/implementations/LinearAlgebra.jl
test/matmul.jl

Fix Vector-AdjVector product

---

src/broadcast.jl
test/broadcast.jl

Fix broadcast for mis-matched arrays

---

.github/workflows/downstream.yml
src/broadcast.jl

Part of https://github.com/jump-dev/JuMP.jl/issues/2999
Much of the CI script was taken from https://github.com/SciML/OrdinaryDiffEq.jl/blob/master/.github/workflows/Downstream.yml

Add integration test for CI and fix JuMP

---

.github/workflows/aqua.yml
src/dispatch.jl
src/interface.jl

Fix ambiguities and re-enable Aqua

---

src/interface.jl
test/interface.jl

Closes https://github.com/jump-dev/MutableArithmetics.jl/issues/164

Fix promote_operation for irrational numbers

---

src/implementations/BigFloat.jl
src/implementations/BigInt.jl
src/implementations/Rational.jl
src/interface.jl
src/shortcuts.jl
test/big.jl

Closes https://github.com/jump-dev/MutableArithmetics.jl/issues/167

Simplify rationals on addition and substraction

---

src/implementations/SparseArrays.jl
test/SparseArrays.jl

Follows https://github.com/jump-dev/MutableArithmetics.jl/pull/173.
I'm not sure which is more concerning: that these methods were added without tests, or that it took so long to find the bugs, which means that no one is probably using them?

Fix methods and add tests for SparseArrays.jl

---

src/dispatch.jl

Part of #178 
There's probably going to be a whole series of these PRs.

dispatch.jl: simplify number * sparse matrix

---

src/dispatch.jl

dispatch.jl: remove work-arounds for Julia 1.0

---

src/rewrite_generic.jl
test/rewrite_generic.jl

Support splatting in rewrite_generic.jl

---

Project.toml

Prep for v1.1.0

---

src/implementations/BigFloat.jl
test/bigfloat_neg_abs.jl
test/runtests.jl

Adapted from -(x::BigFloat) in Base.MPFR in mpfr.jl
Fixes #190
Fixes #191

add BigFloat negation and absolute value

---

src/implementations/BigFloat.jl
test/bigfloat_dot.jl
test/runtests.jl

buffered_operate_to! for BigFloat dot product

---

test/bigfloat_dot.jl
test/bigfloat_fma.jl
test/bigfloat_neg_abs.jl

... instead of reimplementing it ad-hoc

in tests, use MA.copy_if_mutable for copying

---

src/rewrite.jl

Clarify docstring of rewrite macro

---

Project.toml

A bunch of new stuff in here, largely due to @nsajko and @araujoms: https://github.com/jump-dev/MutableArithmetics.jl/compare/v1.3.3...master

Prep for v1.4.0

---

src/implementations/LinearAlgebra.jl
test/matmul.jl

Fix Vector*Transpose{Vector}

---

Project.toml

@blegat take a read over https://github.com/jump-dev/MutableArithmetics.jl/compare/v1.4.0...master to check you're happy.

Prep for v1.4.1

---

src/dispatch.jl
test/dispatch.jl
test/dummy.jl

The product of a Complex number with an Hermitian matrix is not an Hermitian matrix. We should probably still
before we merge
Closes https://github.com/jump-dev/MutableArithmetics.jl/issues/264

Fix product of Complex with Hermitian

---

src/rewrite.jl
test/rewrite.jl

x-ref https://github.com/jump-dev/JuMP.jl/issues/3736
I'll leave the JuMP issue open for now to add tests there.

Implement Base.zero(::Type{MA.Zero})

---

src/implementations/SparseArrays.jl
test/SparseArrays.jl

This is currently a type piracy in https://github.com/JuliaAlgebra/StarAlgebras.jl/pull/21

Implement zero for SparseVector

---

README.md

Mention InPlace.jl in README

---

Project.toml

There's a small risk for code in the wild since we're now rewriting code that we didn't before.

Prep for v1.5.0

---

src/dispatch.jl
test/dispatch.jl

Fix sum(::AbstractArray{<:AbstractMutable}; dims)

---

src/implementations/LinearAlgebra.jl
test/interface.jl

Fix similar_array_type for SubArray

---

src/implementations/BigInt.jl
src/implementations/Rational.jl
test/interface.jl

Needed for https://github.com/JuliaPolyhedra/Polyhedra.jl/pull/343

Fix dot product between Rational{Int} and Rational{BigInt}
